
language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_API_LEVEL = 28
    - ANDROID_BUILD_TOOLS_VERSION = 25.0.0
    - CODECOV_TOKEN=${CODECOV_TOKEN}
    - ADB_INSTALL_TIMEOUT=8
android:
  components:
    - tools
    - tools
    - platform-tools
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - build-tools-25.0.0
    - android-25
    - android-24
    - sys-img-armeabi-v7a-android-24

before_install:
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "platforms;android-28"
  - pip install --user codecov

before_script:
  - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew check build jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)

after_success:
  - codecov
