language: android
jdk: oraclejdk8
env:
  global:
  - ANDROID_API_LEVEL = 28
  - ANDROID_BUILD_TOOLS_VERSION = 25.0.0
  - CODECOV_TOKEN=${CODECOV_TOKEN}
  - ANDROID_ABI = armeabi-v7a
  - ANDROID_TARGET = android-28
android:
  components:
  - tools
  - platform-tools
  - extra-android-m2repository
  - build-tools-${ANDROID_BUILD_TOOLS_VERSION}
  - android-28
  - $ANDROID_TARGET
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

before_install:
- yes | sdkmanager "platforms;android-28"
- pip install --user codecov

before_script:
- echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell setprop dalvik.vm.dexopt-flags v=n,o=v

script:
- ./gradlew jacocoTestReport
- bash <(curl -s https://codecov.io/bash)

after_success:
- codecov
