
language: android
jdk: oraclejdk8
env:
  global:
  - ANDROID_API_LEVEL = 27
  - ANDROID_BUILD_TOOLS_VERSION = 21.1.1
  - CODECOV_TOKEN=${CODECOV_TOKEN}
android:
  components:
  - tools
  - platform-tools
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - build-tools-23.0.5
  - android-22
  - sys-img-x86-android-27

before_install:
- yes | sdkmanager "platforms;android-27"
- pip install --user codecov

before_script:
- echo no | android create avd --force -n test -t android-27 --abi x86
- emulator -avd test -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &

script:
- ./gradlew jacocoTestReport
- bash <(curl -s https://codecov.io/bash)

after_success:
- codecov
